name: social_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^13.2.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  # State Management
  provider: ^6.1.2

  # Image Picker
  image_picker: ^1.0.7

  # UI Extras
  cached_network_image: ^3.3.1
  timeago: ^3.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true